### ISSUE TITLE
Zoom and pan.

### ISSUE THREAD

**Issue by eMonolith** [Fabus1184/PulseSpectralyzer#1]
It would be good to zoom the spectrum and pan with arrow keys.

**Comment by Fabus1184** [comment]
Hey there, do you still need this?

**Comment by eMonolith** [comment]
Hello. I don't really need anything, but it would be good to zoom and pan left and right.


     On Wednesday, April 24, 2024 at 05:24:50 PM EDT, Fabian Lippold ***@***.***> wrote:  
 
 


Hey there, do you still need this?

**Comment by Fabus1184** [comment]
Yeah, I think I'll rewrite this in Rust with a real UI to also include audio options and stuff to replace the hardcoded values everywhere.

**Comment by eMonolith** [comment]
Hello, 

 I don't know about rust and you have a good program, but I think it would be good to reduce cpu usage.

I know of a program that does the job and is less intense on the cpu.


     On Thursday, April 25, 2024 at 10:16:52 AM EDT, Fabian Lippold ***@***.***> wrote:  
 
 


Yeah, I think I'll rewrite this in Rust with a real UI to also include audio options and stuff to replace the hardcoded values everywhere.

**Comment by Fabus1184** [comment]
I started rewriting the program in Rust, it should already work as expected. The graph can be scrolled and zoomed and everything else. This should also be a little bit less CPU-intensive.

**Comment by eMonolith** [comment]
I am not ready to download anything yet, I am still looking at Rust... 

It looks cool and I am impressed you did all that work in the amount of time you have.

I myself am working on an audio spectrum analyzer using X11, kissfft, and alsa.


     On Monday, April 29, 2024 at 10:09:10 PM EDT, Fabian Lippold ***@***.***> wrote:  
 
 


I started rewriting the program in Rust, it should already work as expected. The graph can be scrolled and zoomed and everything else. This should also be a little bit less CPU-intensive.
